# TODO: Bind port 8888 to 8888 to enable prometheus metrics access

version: '3'
services:
  vernemq:
    build: vernemq/
    image: hermes/vernemq
    restart: always
    ports:
      - "1883:1883"
      - "8080:8080"
    container_name: hermes_vernemq
    links:
      - mongodb
    networks: 
      - hermes

  mongodb:
    build: mongodb/
    image: hermes/mongo
    restart: always
    container_name: hermes_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
       - $HOME/data:/data/db
    networks: 
      - hermes

  mongo-express:
    image: mongo-express
    container_name: hermes_mongoexpress
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      - hermes

  redis-sessions-cache:
    image: redis:4
    container_name: hermes_redis-sessions-cache
    restart: always
    ports:
      - "6379:6379"
    restart: always
    networks: 
      - hermes

  redis-real-time:
    image: redis:4
    container_name: hermes_redis-real-time
    restart: always
    ports:
      - "6380:6379"
    restart: always
    networks: 
      - hermes

networks:
  hermes:
    driver: "bridge"